### ISSUE TITLE
interaction issue on mobile version

### ISSUE THREAD

**Issue by jjhesk** [saibotd/libgdxjam2015entry#5]
doesnt zoom in and zoom out in the main stage.

``` java
 public Stage () {
        this(new ScalingViewport(Scaling.stretch, Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), new OrthographicCamera()),
            new SpriteBatch());
        ownsBatch = true;
    }
```

**Comment by saibotd** [comment]
This was a gamejam entry. The Android build was never finished and the desktop version is probably riddled with bugs ;)
Feel free to fiddle around with the code base, but we won't accept any pull requests, nor will we commit changes to this repo.
